### ISSUE TITLE
SO THAT I can transfer multiple feast days to a Sunday, I WANT TO specify more than one secondary feast

### ISSUE THREAD

**Issue by kroll-101** [jftsang/pypew#18]
e.g. Sunday 23rd April 2023, Easter II would transfer collects for BOTH St George and St Mark. At the moment I can select only one or the other.

**Comment by jftsang** [comment]
Is it only the collects that are transferred?

**Comment by MonEstCha** [comment]
@kroll-101, is this ticket actually closed (given the merge)?
