### ISSUE TITLE
As USER, SO THAT I can check changes year to year, I WANT TO generate .docxs with date of service on them

### ISSUE THREAD

**Issue by kroll-101** [jftsang/pypew#19]
e.g. Easter III one year will not be the same as Easter III the next. Secondary collects may be different. Dates and celebrants might be different. 

Current files produced will overwrite if not careful, and make it hard to also track what happens year to year if we e.g. decide to do something special one year for a particular feast, etc.

Could the output filename at least include the year of the service (e.g. 2023 Easter III), but perhaps the date of the service it is generated for (e.g. 2023-04-30 Easter III.docx)

**Comment by jftsang** [comment]
Done
<img width="1009" alt="image" src="https://user-images.githubusercontent.com/119445/233696994-b2746f5c-5161-48e4-ad0d-5bb4cf7bcf34.png">
