### ISSUE TITLE
As USER, SO THAT I can generate pewsheets for dumb days I WANT TO be able to list Communion Plainsong (sung by cantor)

### ISSUE THREAD

**Issue by kroll-101** [jftsang/pypew#20]
Ideally with an option to select which verses are sung, as rarely will it be all of them.

**Comment by jftsang** [comment]
Is the Communion Plainsong necessarily something from NEH or can it be something else?

**Comment by kroll-101** [comment]
Almost always from NEH (it hasn't NOT been from NEH in the last 4-5 years). If not, it is highly likely the text will be in the NEH somewhere anyway.

I'm about to edit the description too...

**Comment by kroll-101** [comment]
Closing this issue since dumb days now don't feature Communion Plainsong.
