### ISSUE TITLE
Title of typical Pew Sheet should be Sung Mass 

### ISSUE THREAD

**Issue by kroll-101** [jftsang/pypew#23]
Not the principal feast.![Screenshot_20230830-155811~3.png](https://github.com/jftsang/pypew/assets/60220648/6a37580a-6405-4ffa-b0e4-d1e83a37dbc6)

**Comment by jftsang** [comment]
![image](https://github.com/jftsang/pypew/assets/119445/0f391707-2628-4d4f-83ca-ac35c880cc50)
