### ISSUE TITLE
Headings should have no paragraph space after them

### ISSUE THREAD

**Issue by kroll-101** [jftsang/pypew#24]
Or body text should have no spacing before it. I.e. Those indicated here ![Screenshot_20230830-160140~2.png](https://github.com/jftsang/pypew/assets/60220648/5e7e4845-3588-45b1-a62b-2c71db84d42b)

should have 0 spacing

**Comment by jftsang** [comment]
![image](https://github.com/jftsang/pypew/assets/119445/6a43106c-2826-4044-98fc-e41ad4d98493)
