### ISSUE TITLE
First line of hymn should be italicised

### ISSUE THREAD

**Issue by kroll-101** [jftsang/pypew#25]
But number and NEH should be normal.![Screenshot_20230830-160140~3.png](https://github.com/jftsang/pypew/assets/60220648/86d90967-8bf5-405d-abf8-a2ae3bdf3656)

**Comment by jftsang** [comment]
![image](https://github.com/jftsang/pypew/assets/119445/6a43106c-2826-4044-98fc-e41ad4d98493)
